site_name: Computer Science 101

repo_url: https://github.com/cs-ufm/cs101-2020

theme:
  name: material
  palette:
    primary: deep blue
    accent: red

  logo: 'img/logo.png'


plugins:
  - search
  #- markdownextradata: {}
markdown_extensions:
  - codehilite
  - footnotes
  - admonition
  - meta
  - toc:
        permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.mark

  - pymdownx.extra

  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.smartsymbols

nav:
  - Home: index.md
  - Projects:
      - Overview: projects/projects.md
      - 1. Hangman:
            1. Instrucciones: projects/hangman/index.md
            2. Forma de Entrega: projects/hangman/para_entregar.md
      - 2. Airline Ticket Reservation:
            1. Instrucciones: projects/airline/index.md
            2. Ejemplo: projects/airline/ejemplo.md
            3. Appendix: projects/airline/appendix.md
            4. Entrega: projects/airline/entrega.md
      - 3. Mini Proyectos:
            1. Calculadora: projects/mini-proyectos/1.calc.md
            2. Piedra Papel Tijera: projects/mini-proyectos/2.ppt.md
  - HDT:
    - "hdt/index.md"
    - "C Punteros": hdt/c.pointers.md
